# manifests/base/comment-service/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: comment-service
spec:
  selector:
    matchLabels:
      app: comment-service
  template:
    metadata:
      labels:
        app: comment-service
    spec:
      containers:
      - name: comment-service
        image: ${ECR_REGISTRY}/blog-platform/comment-service:latest
        ports:
        - containerPort: 8083