# manifests/blog/post-service/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/post-service

namespace: uat

images:
- name: ${ECR_REGISTRY}/blog-platform/post-service
  newName: ${ECR_REGISTRY}/blog-platform/post-service
  newTag: 1.0.0-rc  # This will be updated by ArgoCD Image Updater