# manifests/blog/comment-service/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# - ../../base/frontend
- frontend-service.yaml  # <-- include your Service
- frontend-deployment.yaml  # <-- optionally override base Deployment too

namespace: qa

images:
- name: 575108917104.dkr.ecr.us-east-1.amazonaws.com/blog-platform/frontend
  newName: 575108917104.dkr.ecr.us-east-1.amazonaws.com/blog-platform/frontend
  newTag: 2.4.0-qa  # Updated by CI/CD pipeline