# manifests/blog/comment-service/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/frontend
- ../ingress.yaml  # Reference the ingress from the environment directory

namespace: qa

images:
- name: ${ECR_URL}/blog-platform/frontend
  newName: ${ECR_URL}/blog-platform/frontend
  newTag: 1.0.0-qa  # This will be updated by ArgoCD Image Updater