# manifests/blog/comment-service/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/frontend

namespace: qa

images:
- name: ${ECR_REGISTRY}/blog-platform/frontend
  newName: ${ECR_REGISTRY}/blog-platform/frontend
  newTag: 1.0.0-qa  # This will be updated by ArgoCD Image Updater