# Active Service
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: blog
  labels: green
spec:
  selector:
    app: frontend
    version: green
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
---
# Preview Service
apiVersion: v1
kind: Service
metadata:
  name: frontend-preview
  namespace: blog
spec:
  selector:
    app: frontend
    version: blue
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP