apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: frontend
  namespace: blog
spec:
  replicas: 2
  revisionHistoryLimit: 5  # Increased to store more revisions for rollback
  selector:
    matchLabels:
      app: frontend
  strategy:
    blueGreen:
      activeService: frontend
      previewService: frontend-preview
      autoPromotionEnabled: false  # Manual promotion
      scaleDownDelaySeconds: 300  # Wait 5 minutes before scaling down old version
      prePromotionAnalysis:
        templates:
        - templateName: smoke-tests
        args:
        - name: service-name
          value: frontend-preview
      postPromotionAnalysis:
        templates:
        - templateName: success-rate
        args:
        - name: service-name
          value: frontend
      abortScaleDownDelaySeconds: 600  # 10 minutes to abort rollout and scale back up after a failed promotion
      previewMetadata:
        labels:
          version: blue
      activeMetadata:
        labels:
          version: green
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: 575108917104.dkr.ecr.us-east-1.amazonaws.com/blog-platform/frontend:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 3
          failureThreshold: 3
          timeoutSeconds: 2
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10
          failureThreshold: 3
          timeoutSeconds: 2