# Active Service
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: blog
  labels: 
    color: green
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
---
# Preview Service
apiVersion: v1
kind: Service
metadata:
  name: frontend-preview
  namespace: blog
  labels:
    color: blue
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP