# manifests/prod/frontend/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- frontend-service.yaml
- frontend-deployment.yaml

namespace: blog

images:
- name: 575108917104.dkr.ecr.us-east-1.amazonaws.com/blog-platform/frontend
  newName: 575108917104.dkr.ecr.us-east-1.amazonaws.com/blog-platform/frontend
  newTag: 2.3.0  # Updated by CI/CD pipeline