# manifests/blog/user-service/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/user-service

namespace: qa

images:
- name: ${ECR_URL}/blog-platform/user-service
  newName: ${ECR_URL}/blog-platform/user-service
  newTag: 1.0.0-qa  # This will be updated by ArgoCD Image Updater