# manifests/blog/user-service/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/user-service

namespace: qa

images:
- name: http://575108917104.dkr.ecr.us-east-1.amazonaws.com//blog-platform/user-service
  newName: http://575108917104.dkr.ecr.us-east-1.amazonaws.com//blog-platform/user-service
  newTag: 1.0.0-qa  # This will be updated by ArgoCD Image Updater