# Comment Service Service
# manifests/qa/comment-service/comment-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: comment-service
  namespace: qa
spec:
  selector:
    app: comment-service
  ports:
  - port: 8083
    targetPort: 8083
  type: ClusterIP