# Comment Service Service
apiVersion: v1
kind: Service
metadata:
  name: comment-service
  namespace: qa
spec:
  selector:
    app: comment-service
  ports:
  - port: 8083
    targetPort: 8083
  type: ClusterIP