# manifests/blog/comment-service/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: qa

resources:
# - ../../base/comment-service
- comment-service.yaml  # <-- include your Service
- comment-deployment.yaml  # <-- optionally override base Deployment too

images:
- name: 575108917104.dkr.ecr.us-east-1.amazonaws.com/blog-platform/comment-service
  newName: 575108917104.dkr.ecr.us-east-1.amazonaws.com/blog-platform/comment-service
  newTag: 2.1.0-qa  # Updated by CI/CD pipeline