# manifests/blog/comment-service/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/comment-service

namespace: qa

images:
- name: 575108917104.dkr.ecr.us-east-1.amazonaws.com/blog-platform/comment-service
  newName: 575108917104.dkr.ecr.us-east-1.amazonaws.com/blog-platform/comment-service
  newTag: 1.0.0-qa  # This will be updated by ArgoCD Image Updater