# manifests/base/post-service/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-service
spec:
  selector:
    matchLabels:
      app: post-service
  template:
    metadata:
      labels:
        app: post-service
    spec:
      containers:
      - name: post-service
        image: ${ECR_URL}/blog-platform/post-service:latest
        ports:
        - containerPort: 8082