# Active Service
# manifests/prod/comment-service/comment-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: comment-service
  namespace: blog
  labels: 
    color: green
spec:
  selector:
    app: comment-service
  ports:
  - port: 8083
    targetPort: 8083
  type: ClusterIP
---
# Preview Service
apiVersion: v1
kind: Service
metadata:
  name: comment-service-preview
  namespace: blog
  labels:
    color: blue
spec:
  selector:
    app: comment-service
  ports:
  - port: 8083
    targetPort: 8083
  type: ClusterIP