# manifests/prod/comment-service/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- comment-service.yaml
- comment-deployment.yaml

namespace: blog

images:
- name: 575108917104.dkr.ecr.us-east-1.amazonaws.com/blog-platform/comment-service
  newName: 575108917104.dkr.ecr.us-east-1.amazonaws.com/blog-platform/comment-service
  newTag: 2.3.0  # Updated by CI/CD pipeline