# manifests/blog/frontend/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# - ../../base/frontend
- frontend-service.yaml  # <-- include your Service
- frontend-deployment.yaml  # <-- optionally override base Deployment too

namespace: uat

images:
- name: 575108917104.dkr.ecr.us-east-1.amazonaws.com/blog-platform/frontend
  newName: 575108917104.dkr.ecr.us-east-1.amazonaws.com/blog-platform/frontend
  newTag: 1.1.0-rc  # Updated by CI/CD pipeline