# manifests/blog/frontend/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/frontend

namespace: uat

images:
- name: http://575108917104.dkr.ecr.us-east-1.amazonaws.com/blog-platform/frontend
  newName: http://575108917104.dkr.ecr.us-east-1.amazonaws.com/blog-platform/frontend
  newTag: 1.0.0-rc  # This will be updated by ArgoCD Image Updater