# manifests/blog/user-service/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# - ../../base/user-service
- user-service.yaml  # <-- include your Service
- user-deployment.yaml  # <-- optionally override base Deployment too

namespace: uat

images:
- name: 575108917104.dkr.ecr.us-east-1.amazonaws.com/blog-platform/user-service
  newName: 575108917104.dkr.ecr.us-east-1.amazonaws.com/blog-platform/user-service
  newTag: 1.0.1-rc  # Updated by CI/CD pipeline