# manifests/blog/post-service/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# - ../../base/post-service
- post-service.yaml  # <-- include your Service
- post-deployment.yaml  # <-- optionally override base Deployment too

namespace: blog

images:
- name: 575108917104.dkr.ecr.us-east-1.amazonaws.com/blog-platform/post-service
  newName: 575108917104.dkr.ecr.us-east-1.amazonaws.com/blog-platform/post-service
  newTag: 1.0.1  # Updated by CI/CD pipeline