# manifests/prod/post-service/post-service.yaml
# Active Service
apiVersion: v1
kind: Service
metadata:
  name: post-service
  namespace: blog
  labels: 
    color: green
spec:
  selector:
    app: post-service
  ports:
  - port: 8082
    targetPort: 8082
  type: ClusterIP
---
# Preview Service
apiVersion: v1
kind: Service
metadata:
  name: post-service-preview
  namespace: blog
  labels:
    color: blue
spec:
  selector:
    app: post-service
  ports:
  - port: 8082
    targetPort: 8082
  type: ClusterIP