# Active Service
apiVersion: v1
kind: Service
metadata:
  name: post-service
  namespace: blog
  labels: green
spec:
  selector:
    app: post-service
    version: green
  ports:
  - port: 8082
    targetPort: 8082
  type: ClusterIP
---
# Preview Service
apiVersion: v1
kind: Service
metadata:
  name: post-service-preview
  namespace: blog
spec:
  selector:
    app: post-service
    version: blue
  ports:
  - port: 8082
    targetPort: 8082
  type: ClusterIP