# uat-apps.yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: blog-platform-uat
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: comment-service
        path: manifests/uat/comment-service
      - name: post-service
        path: manifests/uat/post-service
      - name: frontend
        path: manifests/uat/frontend
      - name: user-service
        path: manifests/uat/user-service
      - name: ingress  # Add this new element
        path: manifests/uat  # Path to the directory containing ingress.yaml
  template:
    metadata:
      name: '{{name}}-uat'
      annotations:
        argocd-image-updater.argoproj.io/image-list: '{{name}}=http://575108917104.dkr.ecr.us-east-1.amazonaws.com//blog-platform/{{name}}'
        argocd-image-updater.argoproj.io/{{name}}.update-strategy: newest-build
        argocd-image-updater.argoproj.io/{{name}}.allow-tags: regexp:[0-9.]+\-rc$
        argocd-image-updater.argoproj.io/write-back-method: git
        argocd-image-updater.argoproj.io/git-branch: main
        argocd-image-updater.argoproj.io/write-back-target: kustomization
    spec:
      project: default
      source:
        repoURL: https://github.com/nannanav/blog-infra.git
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: uat
      syncPolicy:
        automated:
          prune: true
          selfHeal: true