# manifests/base/frontend/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: 575108917104.dkr.ecr.us-east-1.amazonaws.com/blog-platform/frontend:latest
        ports:
        - containerPort: 8080