# Active Service
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: blog
  labels: green
spec:
  selector:
    app: user-service
    version: green
  ports:
  - port: 8081
    targetPort: 8081
  type: ClusterIP
---
# Preview Service
apiVersion: v1
kind: Service
metadata:
  name: user-service-preview
  namespace: blog
spec:
  selector:
    app: user-service
    version: blue
  ports:
  - port: 8081
    targetPort: 8081
  type: ClusterIP