# manifests/prod/user-service/user-service.yaml
# Active Service
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: blog
  labels: 
    color: green
spec:
  selector:
    app: user-service
  ports:
  - port: 8081
    targetPort: 8081
  type: ClusterIP
---
# Preview Service
apiVersion: v1
kind: Service
metadata:
  name: user-service-preview
  namespace: blog
  labels:
    color: blue
spec:
  selector:
    app: user-service
  ports:
  - port: 8081
    targetPort: 8081
  type: ClusterIP