name: CI/CD Pipeline

on:
  schedule:
    - cron: '0 0 * * *'  # Nightly build at midnight UTC
  workflow_dispatch:      # Manual trigger option

jobs:
  versioning:
    runs-on: ubuntu-latest
    outputs:
      changed_services: ${{ steps.detect_changes.outputs.changed_services }}
    steps:
      - name: Checkout the infra repo
        uses: actions/checkout@v3